steps:
  - name: ":docker: bootstrap monorepo image"
    plugins:
      docker-compose#v1.5.2:
        build: fusion-release
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  # Just manually upload steps for now until we can dynamically generate the pipeline
  # - name: ":pipeline: generate monorepo steps"
  #   command: "node generatePipeline.js"
  #   plugins:
  #     docker-compose#v1.5.2:
  #       run: fusion-release
  #   agents:
  #     queue: workers
  - name: "fusion-plugin-i18n-react test"
    command: "cd packages/fusion-plugin-i18n-react && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-universal-logger test"
    command: "cd packages/fusion-plugin-universal-logger && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-universal-events-react test"
    command: "cd packages/fusion-plugin-universal-events-react && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-universal-events test"
    command: "cd packages/fusion-plugin-universal-events && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-test-utils test"
    command: "cd packages/fusion-test-utils && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-service-worker test"
    command: "cd packages/fusion-plugin-service-worker && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-styletron-react test"
    command: "cd packages/fusion-plugin-styletron-react && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-rpc-redux-react test"
    command: "cd packages/fusion-plugin-rpc-redux-react && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-rpc-redux test"
    command: "cd packages/fusion-rpc-redux && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-rpc test"
    command: "cd packages/fusion-plugin-rpc && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-redux-action-emitter-enhancer test"
    command: "cd packages/fusion-plugin-redux-action-emitter-enhancer && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-react-router test"
    command: "cd packages/fusion-plugin-react-router && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-react-redux test"
    command: "cd packages/fusion-plugin-react-redux && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-react test"
    command: "cd packages/fusion-react && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-node-performance-emitter test"
    command: "cd packages/fusion-plugin-node-performance-emitter && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-react-async test"
    command: "cd packages/fusion-react-async && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "eslint-config-fusion test"
    command: "cd packages/eslint-config-fusion && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-i18n test"
    command: "cd packages/fusion-plugin-i18n && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-error-handling test"
    command: "cd packages/fusion-plugin-error-handling && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-jwt test"
    command: "cd packages/fusion-plugin-jwt && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-csrf-protection-react test"
    command: "cd packages/fusion-plugin-csrf-protection-react && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-csrf-protection test"
    command: "cd packages/fusion-plugin-csrf-protection && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-browser-performance-emitter test"
    command: "cd packages/fusion-plugin-browser-performance-emitter && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-core test"
    command: "cd packages/fusion-core && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-cli test"
    command: "cd packages/fusion-cli && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "browser-tests test"
    command: "cd packages/browser-tests && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-apollo-universal-client test"
    command: "cd packages/fusion-apollo-universal-client && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-apollo test"
    command: "cd packages/fusion-apollo && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-plugin-font-loader-react test"
    command: "cd packages/fusion-plugin-font-loader-react && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-scaffolder test"
    command: "cd packages/fusion-scaffolder && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
  - name: "fusion-tokens test"
    command: "cd packages/fusion-tokens && yarn test"
    agents:
      queue: workers
    plugins:
      "docker-compose#v1.5.2":
        run: "fusion-release"
