steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose#v1.5.2:
        build: fusion-release
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
